export const metadata = {
  title: 'Auth',
  description: 'Generated by create next app',
}
export default function Auth ({ children }) {
    return (
      <>
        <div className="w-50">
          <h1>hola</h1>

          {children}
        </div>
      </>
    )
  }