import Navbar from "../components/Navbar"
import './globals.css'
import Background from "@/components/Background"
import Head from "next/head"
 
export const metadata = {
  title: 'Copy AI',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <Head>
          <link rel="icon" href="/Group-8.ico" sizes="any" />
        </Head>
        <body className="bg-primary font-textFont text-fontWhite" >
          <Navbar />
          <Background/>
          {children}
        </body>
      </html>
    )
  }


