import Title from "@/components/Title"
import Navbar from "../components/Navbar"
import './globals.css'
import Button from "@/components/Button"
import Background from "@/components/Background"
import { SquareComponent } from "@/components/SquareComponent"
 
export const metadata = {
  title: 'Copy AI',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body >
          <Background/>
          <SquareComponent/>
          <Title text="FRUTILLA"/>
          <Button text="Probando" />
          <Navbar />

          {children}
        </body>
      </html>
    )
  }